name: cubos_desafio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  get_it: ^9.2.0
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4
  mockito: ^5.6.1

flutter:
  uses-material-design: true

  assets:
    - .env
